### ISSUE TITLE
Amp on/off feature is obsolete.

### ISSUE THREAD

**Issue by archviceroyofspackton** [incompetentfox/xantiaButtonControls#1]
For V1, the on/off toggle feature is not required...it seems slightly buggy as well.  I would suggest commenting it out for now.

I think the DIO should reflect the state of the button it represents.  As in the DIO will remain active (low) while the button is pressed.  This can be achieved by only resetting the DIO when the corresponding AIO reads 5V (no button pressed).

**Comment by incompetentfox** [comment]
The DIO should be behaving in that manner anyway- it should be behaving as follows; start loop > read voltage > conditional event based on voltage > restart loop. The only condition in which the DIO is reset is when the voltage condition is +5v.

Shall comment out the toggle.
