### ISSUE TITLE
AIO reference voltage

### ISSUE THREAD

**Issue by archviceroyofspackton** [incompetentfox/xantiaButtonControls#2]
@incompetentfox There is something spooky going on with the nano AIO.  Without input it reads ~1.4V.  I could expect this of a floating pin.  If you enable internal weak pullups "(digitalWrite(A0, HIGH);", both pins will read 5V until you pull a pin low then it will go low and the other will float again.  If you explicitly set AREF to internal there is similarly weird behaviour.  F' knows why.  It probably does not matter when there will be a 5V pull up on the pin when deployed.

**Comment by incompetentfox** [comment]
Yeah, I reckon that it won't be an issue in deployment- there should never be a situation (bar a broken wire in the loom) where there won't be +5v on the pin.
